# Generated by Django 5.2.1 on 2025-06-01 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('working_field', models.CharField(choices=[('AI', 'Artificial Intelligence'), ('ML', 'Machine Learning'), ('WEB', 'Web Development'), ('MOB', 'Mobile Development'), ('GAME', 'Game Development'), ('DATA', 'Data Science'), ('IOT', 'Internet of Things'), ('CYBER', 'Cybersecurity'), ('VLSI', 'VLSI'), ('OTHER', 'Other')], max_length=20)),
                ('github_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='led_projects', to='authentication.coworkinguser')),
                ('team_members', models.ManyToManyField(blank=True, related_name='projects', to='authentication.coworkinguser')),
            ],
        ),
    ]
