# Generated by Django 5.1.3 on 2025-05-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='working_field',
            field=models.CharField(choices=[('AI', 'Artificial Intelligence'), ('ML', 'Machine Learning'), ('WEB', 'Web Development'), ('MOB', 'Mobile Development'), ('GAME', 'Game Development'), ('DATA', 'Data Science'), ('IOT', 'Internet of Things'), ('CYBER', 'Cybersecurity'), ('VLSI', 'VLSI'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.DeleteModel(
            name='ProjectImage',
        ),
    ]
