# Generated by Django 5.1.3 on 2025-05-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoworkingUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('study_level', models.CharField(choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate'), ('PHD', 'Doctorate'), ('FACULTY', 'Faculty'), ('PROFESSIONAL', 'Professional'), ('OTHER', 'Other')], max_length=20)),
                ('specialization', models.CharField(max_length=100)),
                ('college_name', models.CharField(max_length=200)),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('occupied_seat', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
