# Generated by Django 5.1.3 on 2025-05-22 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_coworkinguser_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coworkinguser',
            old_name='check_in',
            new_name='current_check_in',
        ),
        migrations.RemoveField(
            model_name='coworkinguser',
            name='check_out',
        ),
        migrations.RemoveField(
            model_name='coworkinguser',
            name='occupied_seat',
        ),
        migrations.AddField(
            model_name='coworkinguser',
            name='is_checked_in',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CoworkingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='authentication.coworkinguser')),
            ],
            options={
                'ordering': ['-check_in'],
            },
        ),
    ]
