# Generated by Django 5.1.3 on 2025-05-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_coworkinguser_current_check_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coworkingsession',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='coworkingsession',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='coworkingsession',
            name='is_first_time_discount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coworkingsession',
            name='paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
